{
if ($0 ~ /^[!*r=]/) next
if ($1 == ".") next
semits = $1
delta_semits = $2
if (delta_semits == -12)	{minor_tonic[semits-0] += 1}
if (delta_semits == -12)	{minor_tonic[semits-7] += 2}
if (delta_semits == -11)	{minor_tonic[semits-0] += 5}
if (delta_semits == -10)	{minor_tonic[semits-0] += 1}
if (delta_semits == -9)	{minor_tonic[semits-3] += 1}
if (delta_semits == -9)	{minor_tonic[semits-10] += 2}
if (delta_semits == -8)	{minor_tonic[semits-11] += 2}
if (delta_semits == -8)	{minor_tonic[semits-0] += 1}
if (delta_semits == -7)	{minor_tonic[semits-7] += 33}
if (delta_semits == -7)	{minor_tonic[semits-10] += 2}
if (delta_semits == -7)	{minor_tonic[semits-0] += 37}
if (delta_semits == -7)	{minor_tonic[semits-3] += 3}
if (delta_semits == -6)	{minor_tonic[semits-2] += 2}
if (delta_semits == -6)	{minor_tonic[semits-4] += 1}
if (delta_semits == -5)	{minor_tonic[semits-7] += 85}
if (delta_semits == -5)	{minor_tonic[semits-10] += 18}
if (delta_semits == -5)	{minor_tonic[semits-0] += 13}
if (delta_semits == -5)	{minor_tonic[semits-2] += 31}
if (delta_semits == -5)	{minor_tonic[semits-5] += 5}
if (delta_semits == -4)	{minor_tonic[semits-8] += 13}
if (delta_semits == -4)	{minor_tonic[semits-10] += 11}
if (delta_semits == -4)	{minor_tonic[semits-11] += 6}
if (delta_semits == -4)	{minor_tonic[semits-0] += 4}
if (delta_semits == -4)	{minor_tonic[semits-1] += 1}
if (delta_semits == -4)	{minor_tonic[semits-3] += 128}
if (delta_semits == -4)	{minor_tonic[semits-5] += 1}
if (delta_semits == -4)	{minor_tonic[semits-7] += 9}
if (delta_semits == -3)	{minor_tonic[semits-9] += 4}
if (delta_semits == -3)	{minor_tonic[semits-11] += 15}
if (delta_semits == -3)	{minor_tonic[semits-0] += 166}
if (delta_semits == -3)	{minor_tonic[semits-2] += 46}
if (delta_semits == -3)	{minor_tonic[semits-4] += 4}
if (delta_semits == -3)	{minor_tonic[semits-5] += 12}
if (delta_semits == -3)	{minor_tonic[semits-8] += 1}
if (delta_semits == -3)	{minor_tonic[semits-7] += 55}
if (delta_semits == -2)	{minor_tonic[semits-10] += 148}
if (delta_semits == -2)	{minor_tonic[semits-0] += 417}
if (delta_semits == -2)	{minor_tonic[semits-1] += 2}
if (delta_semits == -2)	{minor_tonic[semits-2] += 8}
if (delta_semits == -2)	{minor_tonic[semits-3] += 375}
if (delta_semits == -2)	{minor_tonic[semits-5] += 427}
if (delta_semits == -2)	{minor_tonic[semits-7] += 27}
if (delta_semits == -2)	{minor_tonic[semits-9] += 1}
if (delta_semits == -2)	{minor_tonic[semits-8] += 52}
if (delta_semits == -1)	{minor_tonic[semits-11] += 94}
if (delta_semits == -1)	{minor_tonic[semits-0] += 2}
if (delta_semits == -1)	{minor_tonic[semits-2] += 588}
if (delta_semits == -1)	{minor_tonic[semits-4] += 10}
if (delta_semits == -1)	{minor_tonic[semits-6] += 19}
if (delta_semits == -1)	{minor_tonic[semits-7] += 139}
if (delta_semits == -1)	{minor_tonic[semits-9] += 36}
if (delta_semits == 0)	{minor_tonic[semits-0] += 350}
if (delta_semits == 0)	{minor_tonic[semits-2] += 104}
if (delta_semits == 0)	{minor_tonic[semits-1] += 1}
if (delta_semits == 0)	{minor_tonic[semits-3] += 248}
if (delta_semits == 0)	{minor_tonic[semits-4] += 3}
if (delta_semits == 0)	{minor_tonic[semits-5] += 154}
if (delta_semits == 0)	{minor_tonic[semits-7] += 389}
if (delta_semits == 0)	{minor_tonic[semits-8] += 17}
if (delta_semits == 0)	{minor_tonic[semits-9] += 4}
if (delta_semits == 0)	{minor_tonic[semits-11] += 7}
if (delta_semits == 0)	{minor_tonic[semits-10] += 72}
if (delta_semits == 1)	{minor_tonic[semits-3] += 336}
if (delta_semits == 1)	{minor_tonic[semits-5] += 5}
if (delta_semits == 1)	{minor_tonic[semits-7] += 19}
if (delta_semits == 1)	{minor_tonic[semits-8] += 106}
if (delta_semits == 1)	{minor_tonic[semits-10] += 28}
if (delta_semits == 1)	{minor_tonic[semits-0] += 89}
if (delta_semits == 2)	{minor_tonic[semits-2] += 364}
if (delta_semits == 2)	{minor_tonic[semits-4] += 5}
if (delta_semits == 2)	{minor_tonic[semits-3] += 1}
if (delta_semits == 2)	{minor_tonic[semits-5] += 277}
if (delta_semits == 2)	{minor_tonic[semits-6] += 1}
if (delta_semits == 2)	{minor_tonic[semits-7] += 280}
if (delta_semits == 2)	{minor_tonic[semits-9] += 29}
if (delta_semits == 2)	{minor_tonic[semits-10] += 22}
if (delta_semits == 2)	{minor_tonic[semits-11] += 3}
if (delta_semits == 2)	{minor_tonic[semits-0] += 87}
if (delta_semits == 3)	{minor_tonic[semits-3] += 165}
if (delta_semits == 3)	{minor_tonic[semits-5] += 42}
if (delta_semits == 3)	{minor_tonic[semits-7] += 1}
if (delta_semits == 3)	{minor_tonic[semits-8] += 12}
if (delta_semits == 3)	{minor_tonic[semits-10] += 63}
if (delta_semits == 3)	{minor_tonic[semits-11] += 1}
if (delta_semits == 3)	{minor_tonic[semits-0] += 2}
if (delta_semits == 3)	{minor_tonic[semits-2] += 7}
if (delta_semits == 4)	{minor_tonic[semits-4] += 1}
if (delta_semits == 4)	{minor_tonic[semits-7] += 96}
if (delta_semits == 4)	{minor_tonic[semits-9] += 3}
if (delta_semits == 4)	{minor_tonic[semits-11] += 7}
if (delta_semits == 4)	{minor_tonic[semits-0] += 5}
if (delta_semits == 4)	{minor_tonic[semits-3] += 1}
if (delta_semits == 4)	{minor_tonic[semits-2] += 21}
if (delta_semits == 5)	{minor_tonic[semits-5] += 24}
if (delta_semits == 5)	{minor_tonic[semits-7] += 63}
if (delta_semits == 5)	{minor_tonic[semits-8] += 2}
if (delta_semits == 5)	{minor_tonic[semits-10] += 3}
if (delta_semits == 5)	{minor_tonic[semits-0] += 166}
if (delta_semits == 5)	{minor_tonic[semits-4] += 1}
if (delta_semits == 5)	{minor_tonic[semits-3] += 37}
if (delta_semits == 6)	{minor_tonic[semits-8] += 3}
if (delta_semits == 6)	{minor_tonic[semits-9] += 1}
if (delta_semits == 7)	{minor_tonic[semits-7] += 72}
if (delta_semits == 7)	{minor_tonic[semits-9] += 1}
if (delta_semits == 7)	{minor_tonic[semits-10] += 9}
if (delta_semits == 7)	{minor_tonic[semits-0] += 7}
if (delta_semits == 7)	{minor_tonic[semits-2] += 6}
if (delta_semits == 7)	{minor_tonic[semits-6] += 1}
if (delta_semits == 7)	{minor_tonic[semits-5] += 1}
if (delta_semits == 8)	{minor_tonic[semits-8] += 1}
if (delta_semits == 8)	{minor_tonic[semits-10] += 2}
if (delta_semits == 8)	{minor_tonic[semits-3] += 11}
if (delta_semits == 9)	{minor_tonic[semits-7] += 8}
if (delta_semits == 10)	{minor_tonic[semits-10] += 1}
if (delta_semits == 11)	{minor_tonic[semits-11] += 5}
if (delta_semits == 12)	{minor_tonic[semits-0] += 2}
if (delta_semits == 12)	{minor_tonic[semits-7] += 5}
#if (delta_semits == U)	{1 r	195}
#if (delta_semits == U)	{2 r	75}
#if (delta_semits == U)	{3 r	18}
#if (delta_semits == U)	{4 r	11}
#if (delta_semits == U)	{5 r	101}
#if (delta_semits == U)	{7 r	3}
#if (delta_semits == U)	{7- r	19}
#if (delta_semits == U)	{r 1	3}
#if (delta_semits == U)	{r 2	14}
#if (delta_semits == U)	{r 3	2}
#if (delta_semits == U)	{r 4	1}
#if (delta_semits == U)	{r 5	36}
#if (delta_semits == U)	{r 7-	2}
#if (delta_semits == U)	{r 1	8}
#if (delta_semits == U)	{r 2	5}
#if (delta_semits == U)	{r 3	18}
#if (delta_semits == U)	{r 3+	2}
#if (delta_semits == U)	{r 4	4}
#if (delta_semits == U)	{r 4+	1}
#if (delta_semits == U)	{r 5	27}
#if (delta_semits == U)	{r 6	4}
#if (delta_semits == U)	{r 6+	1}
#if (delta_semits == U)	{r 7	1}
#if (delta_semits == U)	{r 7-	5}
#if (delta_semits == U)	{r r	7}
#if (delta_semits == U)	{r 1	13}
#if (delta_semits == U)	{r 3	6}
#if (delta_semits == U)	{r 3+	1}
#if (delta_semits == U)	{r 4	5}
#if (delta_semits == U)	{r 4+	1}
#if (delta_semits == U)	{r 5	20}
#if (delta_semits == U)	{r 7-	5}
}
END	{
	for (i=0; i<=11; i++)
		{
		print "Tonic[" i "]: " minor_tonic[i]
		}
	}
