midi test00 | perform
midi test01 | perform
midi test02 | perform
midi test03 | perform
midi test04 | perform
midi test05 | perform
midi test06 | perform
midi test07 | perform
midi test08 | perform
midi -r 4 test09 | perform
midi test10 | perform
midi test11 | perform
midi test12 | perform
midi test13 | perform
midi test14 | perform
midi test15 | perform
midi test16 | perform
midi test17 | perform
midi test18 | perform
midi test19 | perform
midi test20 | perform
midi test21 | perform
midi test22 | perform
midi test23 | perform
midi test24 | perform
midi test25 | perform
midi test26 | perform
midi test27 | perform
midi test28 | perform
midi test29 | perform
midi test30 | perform
midi test31 | perform
midi test32 | perform
midi test33 | perform
midi test34 | perform
