\"    This documentation is copyright 1994 David Huron.
.TH deg 1 "1994 Dec. 4"
.AT 3
.sp 2
.SH "NAME"
.in +2
.in +9
.ti -9
\fBdeg\fR  --  translate selected Humdrum pitch-related representations to relative scale degree (\f(CR**deg\fR)
.in -9
.in -2
.sp 1
.sp 1
.SH "SYNOPSIS"
.in +2
.in +7
.ti -7
\fBdeg\fR  [\fB-tx\fR]  [\fIinputfile\fR ...]  [> \fIoutputfile.deg\fR]
.in -7
.in -2
.sp 1
.sp 1
.SH "DESCRIPTION"
.in +2
The
.B "deg"
command transforms various pitch-related inputs to the corresponding
scale degree.
The command outputs one or more Humdrum \f(CR**deg\fR
spines -- where scale degrees are indicated by the numbers 1 (tonic)
to 7 (leading tone).
Scale degree information can be determined only with reference to some
prevailing key.
For example, the pitch C4 is the tonic (1) in the key of C major, but the
submediant (6) in the key of E minor.
The
.B "deg"
command expects a tandem interpretation indicating the key of the input passage;
.B "deg"
will adapt to specified changes of key within an input.
If no key information is provided prior to the first pitch-related data,
.B "deg"
issues an error message and terminates.
.sp 1
.sp 1
The
.B "deg"
command differs from the (related)
.B "degree"
command in that it outputs
.I "relative"
(rather than
.I "absolute)"
pitch-height information.
Upward pitch motions are indicated by the caret (^), whereas downward
pitch motions are indicated by the lower-case letter `v'.
Hence, the token `1' followed by `^5' means that the ensuing dominant pitch
is above rather than below the preceding tonic pitch.
No absolute pitch-height information is represented.
As in the case of
.B "degree,"
plus and minus signs indicate whether a pitch has been chromatically
raised or lowered.
For example, the pitch A-flat is designated `6-' in the key of C major,
but `6' in the key of C minor.
The harmonic minor scale is assumed for all minor keys.
Thus, B-flat is considered a \(odlowered\(cd seventh degree in C minor,
whereas B natural is considered the \(odnormal\(cd (rather than \(odraised\(cd)
seventh degree.
For some applications, this interpretation of the minor-scale seventh degree
may cause difficulties.
.sp 1
.sp 1
The
.B "deg"
command is able to translate any of the pitch-related
representations listed below.
For descriptions of the various input representations (including \f(CR**deg\fR)
refer to Section 2
.I "(Representation Reference)"
of this reference manual.
.sp 1
.sp 1
It is recommended that output files produced using the
.B "deg"
command should be given names with the distinguishing `.deg' extension.
.sp 1
.TS
l l.
\f(CR**kern\fR	core pitch/duration representation
\f(CR**pitch\fR	American National Standards Institute pitch notation
	(e.g. \(odA#4\(cd)
\f(CR**solfg\fR	French solf\o'e\(ga'ge system (fixed `doh')
\f(CR**Tonh\fR	German pitch system
.TE
.sp 1
.ce
.I "Input representations processed by \fBdeg\fR."
.in -2
.SH "OPTIONS"
.in +2
The
.B "deg"
command provides the following options:
.sp 1
.TS
l l.
\fB-h\fR	displays a help screen summarizing the command syntax
\fB-t\fR	suppresses printing of all but the first note of a group
	of tied \f(CR**kern\fR notes
\fB-x\fR	suppresses printing of non-\f(CR**deg\fR signifiers
.TE
.sp 1
Options are specified in the command line.
.sp 1
.sp 1
The
.B "-t"
option ensures that only a single output value is given for tied \f(CR**kern\fR notes;
the output coincides with the first note of the tie.
.sp 1
.sp 1
In the default operation,
.B "deg"
outputs non-pitch-related signifiers in addition to the degree value.
For example, in the key of D major, the \f(CR**pitch\fR token \(odG5zzz\(cd
will result in the output \(od4zzz\(cd -- that is, after translating
G5 to 4, the \(odzzz\(cd signifiers are retained in the output.
For some applications, echoing non-pitch-related signifiers in the output
is useful.
However, in other situations, the result can prove confusing --
especially, when the non-pitch-related signifiers are numbers.
Consider the case of the \f(CR**kern\fR
token \(od4f#\(cd in the key of D minor;
after translating `\f(CRf#\fR' to `\f(CR3+\fR' (i.e. raised third degree),
the preceding non-pitch-related signifier `\f(CR4\fR' will also be output,
hence the value \f(CR43+\fR -- which may cause confusion.
.sp 1
.sp 1
The
.B "-x"
option is useful for eliminating non-pitch-related signifiers from the output.
For most \f(CR**kern\fR inputs, the
.B "-x"
option is recommended.
.in -2
.sp 1
.sp 1
.SH "EXAMPLES"
.in +2
The following example illustrates the use of
.B "deg."
The input contains four pitch-related spines -- one of which (\f(CR**MIDI\fR)
cannot be processed by
.B "deg."
In addition, there is one non-pitch-related spines (\f(CR**embell\fR).
.sp 1
.TS
l s s l l l
l l l l l l.
!! `deg' example.
**kern	**Tonh	**MIDI	**solfg	**pitch	**embell
*M2/4	*M2/4	*M2/4	*M2/4	*M2/4	*M2/4
*C:	*d:	*G#:	*a:	*F:	*F:
\(eq1	\(eq1	\(eq1	\(eq1	\(eq1	\(eq1
8ee-	Gis2	/60/	do3	F4foo	ct
\.	.	/-60/	.	.	.
8f	H2	/62/	fa3	r	upt
\.	.	/-62/	.	.	.
8dd-	B2	/70/	mi3	E4	ct
\.	.	/-70/	.	.	.
8d--	Cis4	/61/	r	F4	sus
\.	.	/-61/	.	.	.
\(eq2	\(eq2	\(eq2	\(eq2	\(eq2	\(eq2
[4a-	r	.	mi~b3	F4 A4	.
\.	Heses2	.	re3	G4 Bb4	ct
4a-]	C3	/48/ /52/	do3	E4 C5	ct
\.	.	/-48/	.	.	.
\.	H2 E3	/-52/	la3	G4	ct
\(eq3	\(eq3	\(eq3	\(eq3	\(eq3	\(eq3
r	A2 F3	.	r	F4	.
===	===	===	===	===	===
*-	*-	*-	*-	*-	*-
.TE
.sp 1
Executing the command:
.sp 1
.sp 1
.in +2
deg -tx input > output.deg
.in -2
.sp 1
.sp 1
produces the following result:
.sp 1
.TS
l s s l l l
l l l l l l.
!! `deg' example.
**deg	**deg	**MIDI	**deg	**deg	**embell
*M2/4	*M2/4	*M2/4	*M2/4	*M2/4	*M2/4
*C:	*d:	*G#:	*a:	*F:	*F:
\(eq1	\(eq1	\(eq1	\(eq1	\(eq1	\(eq1
3-	4+	/60/	3	1	ct
\.	.	/-60/	.	.	.
v4	^6+	/62/	^6	r	upt
\.	.	/-62/	.	.	.
^2-	v6	/70/	v5	v7	ct
\.	.	/-70/	.	.	.
v2-	^7	/61/	r	^1	sus
\.	.	/-61/	.	.	.
\(eq2	\(eq2	\(eq2	\(eq2	\(eq2	\(eq2
^6-	r	.	v5-	1 ^3	.
\.	v6-	.	v4	v2 ^4	ct
\.	^7-	/48/ /52/	v3	v7 ^5	ct
\.	.	/-48/	.	.	.
\.	v6+ ^2	/-52/	^1	v2	ct
\(eq3	\(eq3	\(eq3	\(eq3	\(eq3	\(eq3
r	v5 ^3	.	r	v1	.
===	===	===	===	===	===
*-	*-	*-	*-	*-	*-
.TE
.sp 1
Both processed and unprocessed spines are output.
Notice that the tied note at the beginning of measure 2 in the \f(CR**kern\fR
spine has been rendered as a single note rather than as two notes
(due to the
.B "-t"
option).
Also notice that the non-pitch-related signifiers (e.g. foo)
in the first notes of the \f(CR**pitch\fR spine have been
stripped away (due to the
.B "-x"
option).
Note that the plus and minus signs merely indicate that a scale
degree has been raised or lowered, but not by how much.
Hence both the D-flat and D double-flat in measure 1 of the
first (\f(CR**kern\fR) spine are rendered as `\f(CR2-\fR'.
.in -2
.sp 1
.sp 1
.SH "FILES"
.in +2
The file \f(CRx_option.awk\fR
is used by this program when the
.B "-x"
option is invoked.
.in -2
.sp 1
.sp 1
.SH "PORTABILITY"
.in +2
\s-1DOS\s+1 2.0 and up, with the \s-1MKS\s+1 Toolkit.
\s-1OS/2\s+1 with the \s-1MKS\s+1 Toolkit.
\s-1UNIX\s+1 systems supporting the
.I "Korn"
shell or
.I "Bourne"
shell command interpreters, and revised
.I "awk"
(1985).
.in -2
.sp 1
.sp 1
.SH "SEE ALSO"
.in +2
\fB**deg\fR (2),
\fB**degree\fR (2), \fBdegree\fR (1),
\fB**kern\fR (2), \fBkern\fR (1),
\fB**pitch\fR (2), \fBpitch\fR (1),
\fB**solfg\fR (2), \fBsolfg\fR (1),
\fB**Tonh\fR (2), \fBtonh\fR (1)
.in -2
