\"    This documentation is copyright 1994 David Huron.
.TH humdrum 1 "1994 Dec. 4"
.AT 3
.sp 2
.SH "NAME"
.in +2
\fBhumdrum\fR  --  general syntax checker for Humdrum files
.in -2
.sp 1
.sp 1
.SH "SYNOPSIS"
.in +2
\fBhumdrum\fR  [\fB-v\fR]  [\fIinputfile\fR ...]
.in -2
.sp 1
.sp 1
.SH "DESCRIPTION"
.in +2
.in +5
.ll -5
.sp 1
[***NOTE:  If you are looking for general information about
the Humdrum Toolkit, invoke the appropriate man page by typing:
.sp 1
.in +2
man Humdrum        (note the upper-case `H').]
.in -2
.in -5
.ll +5
.sp 1
The
.B "humdrum"
command identifies whether an input stream conforms to the Humdrum
representation syntax.
Error messages are issued where appropriate.
If the input conforms to the Humdrum syntax, then the
.B "humdrum"
command produces no output, unless the verbose (\fB-v\fR) option is invoked.
.sp 1
.sp 1
Formally, a Humdrum representation may be defined as any ASCII input
containing zero or more
.I "comments, data records"
or
.I "interpretations"
-- with the restriction that no
.I "data records"
or
.I "local comments"
appear without a prior
.I "exclusive interpretation,"
and that the file maintain a coherent
.I "spine"
organization.
.sp 1
.sp 1
Humdrum comments are records (lines) that begin with an exclamation mark (!).
Local comments begin each active spine with a single exclamation mark,
whereas gobal comments begin with two exclamation marks (!!) at the
beginning of the record.
.sp 1
.sp 1
Humdrum interpretations are records that begin with an asterisk (*).
Tandem interpretations begin each active spine with a single asterisk,
whereas exclusive interpretations begin the record with one or more asterisks
and have at least one active spine beginning with two asterisks.
Spine-path indicators are special types of interpretations that
include any one of the following tokens: *+  *-  *v  *^  or *x.
Spine-path indicators cannot appear on the same line with a tandem
or exclusive interpretation.
.sp 1
.sp 1
Any record that does not begin with either an exclamation mark
of asterisk is a data record.
.sp 1
.sp 1
The following table defines some of the pertinent Humdrum terminology.
.sp 1
.TS
l l.
\fIrecord\fR	a line of text; a sequences of (zero or more)
	  ASCII characters terminated by a carriage
	  return or newline character
\fIdata record\fR	any \fIrecord\fR which is not a \fIcomment\fR
	  or an \fIinterpretation\fR
\fIcomment\fR	a \fIglobal\fR or \fIlocal comment\fR
\fIglobal comment\fR	any \fIrecord\fR beginning with two exclamation
	  marks (!!)
\fIlocal comment\fR	any \fIrecord\fR beginning with a single
	  exclamation mark (!)
\fIinterpretation\fR	an \fIexclusive\fR or \fItandem interpretation\fR,
	  or a \fIspine-path indicator\fR
\fIexclusive interpretation\fR	any \fIrecord\fR beginning with one or
	  more asterisks (**) and having at least one
	  active spine beginning with two asterisks
\fItandem interpretation\fR	any \fIrecord\fR in which each active
	  spine begins with a single asterisk,
	  excluding spine-path indicators
\fIspine-path indicator\fR	one of the following five \fIinterpretations\fR:
	  *+   *-   *v   *^   *x
\fInull token\fR	the period (.) either alone on a single
	  \fIrecord\fR or separated from other
	  characters by tabs
\fIspine\fR	a column of information -- including \fIdata
	  records, local\fR \fIcomments\fR, and
	  \fIinterpretations.\fR
.TE
.sp 1
.ce
.I "Some Humdrum Definitions"
The following files may satisfy the Humdrum syntactical requirements:
.AL
.LI
a file containing data records preceded by at least one
exclusive interpretation
.LI
a file containing only comments and interpretations
.LI
a file containing only interpretations
.LI
a file containing only global comments
.LI
a totally empty file.
.LE
.sp 1
.sp 1
Additional interpretations may be added throughout the file.
Global comments may appear anywhere in the file.
Local comments and data records can appear only after a spine
has been initiated via an exclusive interpretation.
.sp 1
.sp 1
Illegal constructions in Humdrum include the following:
.EQ
delim off
.EN
.AL
.LI
empty record (i.e. a record containing only a carriage return or newline)
.LI
record containing only tabs
.LI
any record beginning with a tab
.LI
any record ending with a tab (except in a global comment)
.LI
any record containing two successive tab characters (except in a global comment)
.LI
any data record with fewer or more spines than the immediately preceding
data or exclusive interpretation record
.LI
spine-path record containing only one join-spine indication
.LI
spine-path record containing only one exchange-spine indication,
or containing more than two exchange-spine indicators.
.LE
.in -2
.sp 1
.sp 1
.SH "SPINE ORGANIZATION"
.in +2
A Humdrum file must maintain a coherent spine organization.
Spines are columns of information separated by tabs.
Each spine must be labelled with an exclusive interpretation.
If the number of spines varies in a given file,
spines must be added, terminated, split, joined, or exchanged using
the appropriate spine path indicators.
Spines may (1) start, (2) terminate, (3) split (into two),
(4) join (\fIn\fR-into-one), and (5) exchange.
.in -2
.sp 1
.TS
l l.
\f(CR*+\fR	- start a new spine
\f(CR*-\fR	- terminate a current spine
\f(CR*^\fR	- split a spine (into two)
\f(CR*v\fR	- join (two or more) spines into one
\f(CR*x\fR	- exchange the position of two spines
.TE
.sp 1
.ce
.I "Spine-path Indicators"
.in +2
The use of various spine-path indicators is illustrated below:
.sp 1
.TS
l l l l l l.
1	2	3
*	*+	*
*	*	**inter	*		(must follow immediately after)
1	2	new	3
.sp 1
.sp 1
1	2	3
*	*-	*
1	3
.sp 1
.sp 1
1	2	3
*	*^	*
1	2a	2b	3
.sp 1
.sp 1
1	2	3
*	*v	*v
1	2&3
.sp 1
.sp 1
1	2	3
*x	*x	*
2	1	3
.sp 1
.sp 1
.T&
l s s s s s
l l l l l l.
More complex examples:
.sp 1
.sp 1
1	2	3	4	5
*	*-	*	*-	*
*v	*v	*v
1&3&5
.sp 1
.sp 1
1	2	3	4
*	*	*v	*v
*	*x	*x
*v	*v	*
1&3&4	2
.sp 1
.sp 1
1	2	3	4
*v	*v	*^	*^
1&2	3a	3b	4a	4b
.sp 1
.sp 1
1	2	3	4	5
*	*-	*	*	*
*v	*v	*	*
*	*^	*
*	*	*+	*
*	*	*	**inter	*
1&3	4a	4b	new	5
.TE
.sp 1
.in -2
.SH "OPTIONS"
.in +2
The
.B "humdrum"
command provides the following options:
.sp 1
.TS
l l.
\fB-h\fR	displays a help screen summarizing the command syntax
\fB-v\fR	verbose mode
.TE
.sp 1
Options are specified in the command line.
.sp 1
.sp 1
The
.B "-v"
option invokes the verbose mode which provides summary information
and statistics concerning the input file.
A list of all of interpretations found in the file is output.
In addition, an inventory of all of the ASCII signifiers (characters) found
in the data records is output.
The total number of data records is also provided, as well as the
number of null tokens encountered.
.sp 1
.sp 1
The verbose summary also produces a number of statistics related
to the spine-organization in the Humdrum file.
Both the minimum and maximum number of spines are identified.
The paths of the various spines through the file are also summarized.
Specifically,
.B "humdrum"
indicates the number of terminated spines, the number of new spines
introduced, the number of joined spines, the number of split spines,
and the number of exchanged spines.
.in -2
.sp 1
.sp 1
.SH "EXAMPLES"
.sp 1
.sp 1
.in +2
The following is a sample input that conforms to the Humdrum syntax.
.in +2
.sp 1
.TS
l s s
l s s
l s s
l l l
l s s
l l l.
!! This is a global comment.
!! The following line specifies three
!! interpretations called "inter":
**inter	**inter	**inter
!! The next line has three local comments.
! flute	! oboe	! fingering
We	are	ASCII
data	tokens	.
We are	data as	well.
.T&
l s s
l s s
l l l.
!! The above three lines are data records.
!! More examples of data records:
76.3	x+y	L(-)%4^
_ _ _	_ _	_ _ _ _ _
>	<	|||
.T&
l s s
l s s
l l l
l s s
l l l.
!! The next data record contains
!! only null tokens:
\.	.	.
!! Some spine-path exchanges:
!Spine1	!Spine2	!Spine3
*x	*x	*
*	*x	*x
!Spine2	!Spine3	!Spine1
Monday	Tuesday	Wednesday
4:00	5:00	6:00PM
.T&
l s s
l l l.
!! Some null comments follow:
!!
!	!	!
.T&
l s s
l l l
l s s
l l l.
!! New exclusive interpretations:
**foo	**bar	**ding
!! A tandem interpretation in spine #2:
*	*bop	*
More	data	tokens.
.T&
l s s
l l l.
!! Some spine-path terminators:
*-	*-	*-
.TE
.sp 1
.in -2
Where the verbose
.B "(-v)"
flag has been selected, the corresponding output for the above file would be:
.sp 1
.sp 1
.nf
Inventory of Interpretations:                 HUMDRUM FILE SUMMARY

        Interpretations  Occurrences
        **inter          3
        **foo            1
        **bar            1
        **ding           1
        *                2
        *bop             1

Inventory of data token signifiers:   %()+-.034567:<>
                                      ACILMPSTW^_
                                      adeklnorstuwxy

Number of global comments:      14    Number of local comments:       4
Maximum # of concurrent spines: 3     Minimum # of concurrent spines: 3
Number of data records:         10    Number of null tokens:          4


Changes in number of spines:
        New spines:        0
        Terminated spines: 3
        Split spines:      0
        Joined spines:     0
        Exchanges spines:  4
.fi
.in -2
.SH "FILES"
.in +2
The
.B "humdrum"
command uses a kornshell script to invoke an executable.
In order to avoid conflict, the executable file is named
\f(CRhumdrum_.exe\fR (\f(CRhumdrum_\fR on \s-1UNIX\s+1) rather than
\f(CRhumdrum.exe\fR.
.in -2
.sp 1
.sp 1
.SH "PORTABILITY"
.in +2
\s-1DOS\s+1 2.0 and up, with the \s-1MKS\s+1 Toolkit.
\s-1OS/2\s+1 with the \s-1MKS\s+1 Toolkit.
\s-1UNIX\s+1 systems supporting the
.I "Korn"
shell or
.I "Bourne"
shell command interpreters, and revised
.I "awk"
(1985).
.in -2
.sp 1
.sp 1
.SH "SEE ALSO"
.in +2
\fBcensus\fR (1),
\fBproof\fR (1)
.in -2
.sp 1
.sp 1
.SH "DIAGNOSTICS"
.in +2
The following list tabulates all of the potential errors and
warnings issued by the
.B "humdrum"
command.
.sp 1
.TS
l l.
ERROR 1:	Record containing add-spine indicator has not been
	  followed by exclusive interpretation for that spine
	  in line 
ERROR 2:	Illegal empty record in line
ERROR 3:	Leading tab in line
ERROR 4:	Trailing tab in line
ERROR 5:	Consecutive tabs in line
ERROR 6:	Missing initial asterisk in interpretation keyword
	  in line
ERROR 7:	Null exclusive interpretation found in line
ERROR 8:	Incorrect number of spines in interpretation record
	  in line
ERROR 9:	Local comment precedes first exclusive interpretation
	  record in line
ERROR 10:	Number of sub-comments in local comment does not match
	  the number of currently active spines
	  in line 
ERROR 11:	Missing initial exclamation mark in local comment
	  in line
ERROR 12:	Data record appears before first exclusive interpretation
	  record in line 
ERROR 13:	Number of tokens in data record does not match the number
	  of currently active spines in line
ERROR 14:	All spines have not been properly terminated in file
ERROR 15:	First exclusive interpretation record contains a null
	  interpretation in line
ERROR 16:	First exclusive interpretation record contains a spine-path
	  indicator in line
ERROR 17:	First exclusive interpretation record contains a
	  non-exclusive interpretation in line
ERROR 18:	Spine-path indicators mixed with keyword interpretations
	  in line
ERROR 19:	Improper number of exchange-path indicators in line
ERROR 20:	Single join-path indicator found at end of interpretation
	  record in line
ERROR 21:	Join-path indicator is not adjacent to another join-path
	  indicator in line
ERROR 22:	Exclusive interpretations do not match for designated
	  join spines in line
ERROR 23:	Leading spaces in token in line
ERROR 24:	Trailing spaces in token in line
ERROR 25:	Consecutive spaces in token in line
ERROR 26:	Multiple-stop contains null token in line
WARNING 1:	Local comment may be mistaken for global comment in line
WARNING 2:	Data token may be mistaken for global comment in line
WARNING 3:	Data token may be mistaken for local comment in line
WARNING 4:	Data token may be mistaken for exclusive interpretation
	  in line
WARNING 5:	Data token may be mistaken for tandem interpretation
	  in line
.TE
.sp 1
.ce
.I "Potential errors and warnings issued by \fBhumdrum\fR."
.in -2
