\"    This documentation is copyright 1994 David Huron.
.TH humver 1 "1994 Dec. 4"
.AT 3
.sp 2
.SH "NAME"
.in +2
\fBhumver\fR  --  display Humdrum toolkit version and copyright information
.in -2
.sp 1
.sp 1
.SH "SYNOPSIS"
.in +2
\fBhumver\fR  [\fB-s\fR]
.in -2
.sp 1
.sp 1
.SH "DESCRIPTION"
.in +2
The
.B "humver"
command tells the user which version or release of the
Humdrum Toolkit is installed or available on a given computer system.
The command also prints copyright information pertaining to the
Humdrum Toolkit.
.in -2
.sp 1
.sp 1
.SH "OPTIONS"
.in +2
The
.B "-s"
option suppresses output and returns a value to the shell corresponding
to the Humdrum Toolkit version number.
(This option is useful in allowing shell programs to determine
the version number without sending output to the standard output.)
.in -2
.sp 1
.sp 1
.SH "PORTABILITY"
.in +2
\s-1DOS\s+1 2.0 and up, with the \s-1MKS\s+1 Toolkit.
\s-1OS/2\s+1 with the \s-1MKS\s+1 Toolkit.
\s-1UNIX\s+1 systems supporting the
.I "Korn"
shell or
.I "Bourne"
shell command interpreters, and revised
.I "awk"
(1985).
.in -2
