\"    This documentation is copyright 1994 David Huron.
.TH midreset 1 "1994 Dec. 4"
.AT 3
.sp 2
.SH "NAME"
.in +2
.in +11
.ti -11
\fBmidreset\fR  -- reset MIDI controller card
.in -11
.in -2
.sp 1
.sp 1
.SH "SYNOPSIS"
.in +2
.in +7
.ti -7
\fBmidreset\fR
.in -7
.in -2
.sp 1
.sp 1
.SH "DESCRIPTION"
.in +2
The
.B "midreset"
command resets the MIDI controller card.
The
.B "midreset"
command is useful if a MIDI application has terminated
abnormally -- leaving the MIDI card unaccessable to further use.
.in -2
.sp 1
.sp 1
.SH "OPTIONS"
.in +2
The
.B "midreset"
command provides only a help option:
.sp 1
.TS
l l.
\fB-h\fR	displays a help screen summarizing the command syntax
.TE
.sp 1
Options are specified in the command line.
.in -2
.sp 1
.sp 1
.SH "PORTABILITY"
.in +2
\s-1DOS\s+1 2.0 and up.
.in -2
.sp 1
.sp 1
.SH "SEE ALSO"
.in +2
\fBperform\fR (1), \fBsmf\fR (1), \fBtacet\fR (1)
.in -2
.sp 1
.sp 1
.SH "REFERENCES"
.in +2
Use of the Music Quest Inc. MIDI library functions is gratefully
acknowledged.
.in -2
